apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: loco
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loco
  minReplicas: 3      
  maxReplicas: 5    
  targetCPUUtilizationPercentage: 60  

